version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - ../../.env.local
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 